routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('admin/login', '\App\Http\Controllers\Admin\Auth\LoginController@login')->name('admin.login')->middleware('admin.guest');
Route::post('admin/onLogin', '\App\Http\Controllers\Admin\Auth\LoginController@onLogin')->name('admin.onLogin')->middleware('admin.guest');

Route::namespace ('\App\Http\Controllers\Admin')->middleware(['admin.auth'])->group(function () {
    //Home Page
    Route::get('/dashboard', 'HomeController@index')->name('home');
    //manage user
    Route::prefix('common')->group(function () {
        Route::get('/delete', 'CommonController@destroy')->name('common.destroy');
        Route::get('/print', 'CommonController@prints')->name('common.print');
        Route::get('/export', 'CommonController@export')->name('common.export');
        Route::post('/import', 'CommonController@import')->name('common.import');
        Route::get('/samplefiledownload', 'CommonController@sampleFileDownload')->name('common.samplefiledownload');

    });

    Route::prefix('admin')->group(function () {
        Route::resource('roles', 'RolesController', ['names' => 'admin.roles']);
        Route::resource('admin', 'Auth\AdminController')->except('update');
        Route::post('/admin/{admin}', 'Auth\AdminController@update')->name('admin.update');
        Route::get('/admin/{admin}', 'Auth\AdminController@show')->name('admin.show');

        Route::get('/profile/{id}', 'Auth\AdminController@profile')->name('admin.profile');
        Route::post('/changePassword', 'Auth\AdminController@changePassword')->name('admin.changePassword');
        Route::post('/admin-role/update/{id}', 'Auth\AdminController@roleUpdate')->name('admin.role.update');
        //Visitor Table
        Route::get('/visitor', 'VisitorController@VisitorIndex')->name('admin.VisitorIndex');
        Route::resource('user', 'UserController', ['names' => 'admin.user'])->except('update');
        Route::post('user/update/{user}', 'UserController@update')->name('admin.user.update');

        Route::get('readNotification',  function()
        {
            Auth::user()->unReadNotifications->markAsRead();
            return redirect()->back();
        })->name('admin.notification.read');

    });

        /**
         * Blog Route Start
         */
        Route::resource('blog', 'Blog\BlogController', ['names' => 'blog']);
        Route::get('/view/{blog}', 'Blog\BlogController@view')->name('blog.view');

        Route::resource('/category', 'Blog\CategoryController');
        Route::get('/category/{category}', 'Blog\CategoryController@show')->name('category.show');

        Route::resource('subcategory' , 'Blog\SubCategoryController');
        Route::get('/subcategory/list', 'Blog\SubCategoryController@ajaxGetData')->name('subcategory.ajaxdata');

        Route::resource('/tag', 'Blog\TagController');



        //manage comment
        Route::prefix('comment')->group(function () {
            Route::get('comment', 'Blog\CommentController@index')->name('comment.list');
            Route::get('approve/approve-list', 'Blog\CommentController@approveList')->name('comment.approve.list');
            Route::get('pending/pending-list', 'Blog\CommentController@pendingList')->name('comment.pending.list');
            Route::get('pending/list/approve/{id}', 'Blog\CommentController@pendingListApprove')->name('comment.pending.list.approve');
            Route::delete('delete/{id}', 'Blog\CommentController@destroy')->name('comment.destroy');
        });

        //filter data
        Route::prefix('filter')->group(function () {
            Route::get('/list', 'Blog\FilterController@index')->name('filter.view');
            Route::get('/list/data', 'Blog\FilterController@filter')->name('filter.list');
            Route::get('/subcategory/list', 'Blog\FilterController@ajaxGetSubcategoryData')->name('filter.getsubcategory');

        });


          /**
         * Blog Route Start
         */

    //manage Contact
    Route::prefix('contact')->group(function () {
        Route::get('/list', 'ContactController@index')->name('contact.index');

    });

    //manage setting
    Route::prefix('setting')->group(function () {
        Route::get('/list', 'SettingController@index')->name('setting.index');
        Route::get('/create', 'SettingController@create')->name('setting.create');
        Route::post('/store', 'SettingController@store')->name('setting.store');
        Route::post('/update/{id}', 'SettingController@update')->name('setting.update');
    });
    //banner
    Route::resource('banners', 'BannerController');

    Route::post('admin/logout', 'Auth\LoginController@onLogout')->name('admin.logout');
});


Route::namespace ('\App\Http\Controllers\Frontend')->group(function () {
    Route::get('/', 'HomeController@index')->name('client.home');
    Route::get('/login', 'Auth\LoginController@index')->name('client.loginProcess')->middleware('guest');
    Route::get('/register', 'Auth\LoginController@create')->name('client.register')->middleware('guest');
    Route::post('/register', 'Auth\LoginController@store')->name('client.regitration')->middleware('guest');
    Route::get('/send-otp', 'Auth\LoginController@sendOtp')->name('client.sendOtp')->middleware('guest');
    Route::post('/login', 'Auth\LoginController@login')->name('client.login')->middleware('guest');
    Route::prefix('user')->middleware('auth')->group(function () {
        Route::get('dashboard', 'User\UserController@index')->name('client.dashboard');
    });
});

app/Http/Controllers/Admin/Blog/FilterController.php
<?php

namespace App\Http\Controllers\Admin\Blog;
use App\Http\Controllers\BaseController;
use App\Models\Category;
use App\Models\Blog;
use App\Models\Subcategory;
use Illuminate\Http\Request;

class FilterController extends BaseController
{
    public function index(){
        return view('admin.pages.filter.index', [
            'prefixname' => 'Search',
            'title' => 'Search List',
            'page_title' => 'Search List',
            'categories' => Category::where('status',1)->get(),
            'subcategories' => Subcategory::where('status',1)->get(),
            'blog' => Blog::where('status',1)->paginate(20),
        ]);
    }

    public function filter(Request $request){

        $category_id = $request->get('category');
        $subcategory_id = $request->get('subcateogry');

        if($category_id && $subcategory_id){
            $story = Blog::where('category_id',$category_id)->where('subcategory_id', $subcategory_id)->where('status',1)->get();
        }
        elseif($category_id){
            $story = Blog::where('category_id',$category_id)->where('status',1)->get();
        }
//        else if($subcategory_id){
//            $story = Blog::where('subcategory_id', $subcategory_id)->where('status',1)->get();
//        }
//        else if($category_id && $subcategory_id){
//            $story = Blog::where('category_id',$category_id)->where('subcategory_id', $subcategory_id)->where('status',1)->get();
//        }
        else {
            $story = null;
        }

        return view('admin.pages.filter.search', [
            'prefixname' => 'Search',
            'title' => 'Search List',
            'page_title' => 'Search List',
            'categories' => Category::where('status',1)->get(),
            'subcategories' => Subcategory::where('status',1)->get(),
            'blog' => $story
        ]);
    }

    public function ajaxGetSubcategoryData(Request $request){
        if($request->ajax()){
            $subcat = Subcategory::where('category_id',$request->category_id)->get()->pluck("full_name","id");
            return response()->json($subcat);
        }
    }
}

resources/views/admin/pages/filter/index.blade.php
@extends('admin.layouts.master')
@section('content')

<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Filter</h2>
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a>
                            </li>
                            <li class="breadcrumb-item active">Filter
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="content-body">
        <!-- Responsive tables start -->
        <div class="row" id="table-responsive">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Filter</h4>
                    </div>

                    <div class="card-body">
                        <form action="{{ route('filter.list') }}" method="get">
                            @csrf
                            <div class="row">

                                <div class="col-xl-4 col-md-6 col-12 mb-1">
                                    <div class="form-group">
                                        <label for="description">Category</label>
                                        <select class="form-control kagawad" name="category" id="category">
                                            <option value="">---- Select Category ----</option>
                                            @foreach($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->nameBn }} ({{ $category->nameEn }})</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-md-6 col-12 mb-1">
                                    <div class="form-group">
                                        <label for="description">Category</label>
                                        <select class="form-control kagawad" name="subcateogry" id="">
                                            <option value="">--- Select Sub Category ----</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <button class="btn btn-success right" type="submit">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="table-responsive p-1">
                        <table  id="dataTable" class="table table-bordered table-striped common-datatables" style="width:100%; padding: 10px">
                            <thead>
                                <tr>
                                    <th scope="col" class="text-nowrap">#</th>
                                    <th>Title</th>
                                    <th>Category</th>
                                    <th>Description</th>
                                    <th>Image</th>
                                    <th scope="col" class="text-nowrap text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($blog as $key => $n)
                                <tr>
                                    <td>{{ ++$key }}</td>
                                    <td>{{ $n->title }}</td>
                                    <td>{{ $n->category->nameBn }}</td>
                                    <td>
                                        {{ \Illuminate\Support\Str::limit($n->description, 100, '') }}
                                        ................
                                    </td>
                                    <td>
                                        @if($n->image != null)
                                        <img src="{{ asset($n->image) }}" style="border-radius: 5px;" width="50" height="50" class="responsive-img mb-10" alt="">
                                        @else
                                        {{-- <img src="{{ asset($n->subcategory->image) }}" style="border-radius: 5px;" width="50" height="50" class="responsive-img mb-10" alt="">--}}
                                        @endif
                                    </td>
                                    {{-- <td>--}}
                                    {{-- <span class="badge {{ $n->status == 1 ? 'blue' : 'red' }}">{{ $n->status == 1 ? 'Active' : 'Deactive' }}</span>--}}
                                    {{-- </td>--}}
                                    <td>
                                        <div class="icon-preview col s6 m3">
                                            <a href="{{ route('blog.view', $n->id) }}" method="GET" title="View">
                                                <i class="material-icons dp48">remove_red_eye</i>
                                            </a>

                                        </div>
                                        {{-- <div class="icon-preview col s6 m3">--}}
                                        {{-- <a href="{{ route('blog.edit', $n->id) }}" method="GET" title="Edit">--}}
                                        {{-- <i class="material-icons dp48">edit</i>--}}
                                        {{-- </a>--}}

                                        {{-- </div>--}}
                                        {{-- <div class="icon-preview col s6 m3">--}}
                                        {{-- <form action="{{ route('blog.delete', $n->id) }}" method="POST">--}}
                                        {{-- {{ csrf_field() }}--}}
                                        {{-- {{ method_field('DELETE') }}--}}
                                        {{-- <button class="btn" type="submit" onclick="return confirm(' you want to delete?');">--}}
                                        {{-- <i class="material-icons dp48">delete</i>--}}
                                        {{-- </button>--}}
                                        {{-- </form>--}}
                                        {{-- </div>--}}

                                    </td>
                                </tr>
                                @empty
                                <p>No replies</p>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- Responsive tables end -->
    </div>
</div>
@endsection
@push('custom-js')
<!-- BEGIN PAGE VENDOR JS-->
<script src="{{asset('admin/app-assets/vendors/data-tables/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/app-assets/vendors/data-tables/js/dataTables.select.min.js')}}"></script>
<!-- END PAGE VENDOR JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('admin/app-assets/js/scripts/data-tables.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{ asset('admin/app-assets/js/scripts/ui-alerts.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{ asset('admin/app-assets/js/scripts/page-users.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<script !src="">
    $('.kagawad').on('change', function() {
        $('.send').prop('disabled', !$(this).val());
    }).trigger('change');

    $("#category").on('change', function() {
        // alert($(this).val())
        var category_id = $(this).val()
        $.ajax({
            url: '/filter/subcategory/list',
            type: "get",
            data: {
                category_id: category_id
            }, // the value of input having id vid
            success: function(response) { // What to do if we succeed
                $('select[name="subcateogry"]').empty();
                $.each(response, function(key, value) {
                    $('select[name="subcateogry"]').append('<option value="' + key + '">' + value + '</option>');

                });
            }
        });

    });
</script>
@endpush

resources/views/admin/pages/filter/search.blade.php
@extends('admin.layouts.master')
@section('prefixname', $prefixname)
@section('title', $title)
@section('page_title', $page_title)
@section('content')
<!-- Page Length Options -->

<!-- users list start -->
<section class="users-list-wrapper section">
    <div class="users-list-filter">
        <div class="card-panel">
            <form action="{{ route('filter.list') }}" method="get">
                @csrf
                <div class="row">

                    <div class="col-xl-4 col-md-6 col-12 mb-1">
                        <div class="form-group">
                            <label for="description">Category</label>
                            <select class="form-control kagawad" name="category" id="category">
                                <option value="">---- Select Category ----</option>
                                @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->nameBn }} ({{ $category->nameEn }})</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-12 mb-1">
                        <div class="form-group">
                            <label for="description">Category</label>
                            <select class="form-control kagawad" name="subcateogry" id="">
                                <option value="">--- Select Sub Category ----</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <button class="btn btn-success right" type="submit">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="users-list-table">
        <div class="card">
            <div class="card-content">
                Total = {{ $blog->count() }}
                <!-- datatable start -->
                <div class="responsive-table p-1">
                    <table  id="dataTable" class="table table-bordered table-striped common-datatables" style="width:100%; padding: 10px">
                        <thead>
                            <tr>
                                <th>SL</th>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($blog as $key => $n)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>{{ $n->title }}</td>
                                <td>{{ $n->category->nameBn }}</td>
                                <td>
                                    {{ \Illuminate\Support\Str::limit($n->description, 100, '') }}
                                    ................
                                </td>
                                <td>
                                    @if($n->image != null)
                                    <img src="{{ asset($n->image) }}" style="border-radius: 5px;" width="50" height="50" class="responsive-img mb-10" alt="">
                                    @else
                                    <img src="{{ asset($n->subcategory->image) }}" style="border-radius: 5px;" width="50" height="50" class="responsive-img mb-10" alt="">
                                    @endif
                                </td>

                                <td>
                                    <a href="{{ route('blog.view', $n->id) }}" class="btn btn-primary">
                                        <i class="fa fa-pencil-square-o"></i>
                                        show
                                    </a>


                                </td>
                            </tr>
                            @empty
                            <div class="card-content red-text">
                                <p>Sorry : No Data Found</p>
                            </div>
                            @endforelse

                        </tbody>
                    </table>
                </div>
                <!-- datatable ends -->

            </div>
        </div>
    </div>
</section>
<!-- users list ends -->

@endsection
@push('custom-css')
<link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/dropify/css/dropify.min.css')}}">

<link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/quill/katex.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/quill/monokai-sublime.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/quill/quill.snow.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('admin/app-assets/vendors/quill/quill.bubble.css')}}">
@endpush
@push('custom-js')
<!-- BEGIN PAGE VENDOR JS-->
<script src="{{asset('admin/app-assets/vendors/data-tables/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/app-assets/vendors/data-tables/extensions/responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('admin/app-assets/vendors/data-tables/js/dataTables.select.min.js')}}"></script>
<!-- END PAGE VENDOR JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('admin/app-assets/js/scripts/data-tables.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{ asset('admin/app-assets/js/scripts/ui-alerts.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{ asset('admin/app-assets/js/scripts/page-users.js')}}"></script>
<!-- END PAGE LEVEL JS-->
<script !src="">
    $('.kagawad').on('change', function() {
        $('.send').prop('disabled', !$(this).val());
    }).trigger('change');

    $("#category").on('change', function() {
        // alert($(this).val())
        var category_id = $(this).val()
        $.ajax({
            url: '/filter/subcategory/list',
            type: "get",
            data: {
                category_id: category_id
            }, // the value of input having id vid
            success: function(response) { // What to do if we succeed
                $('select[name="subcateogry"]').empty();
                $.each(response, function(key, value) {
                    $('select[name="subcateogry"]').append('<option value="' + key + '">' + value + '</option>');

                });
            }
        });

    });
</script>
@endpush