routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('admin/login', '\App\Http\Controllers\Admin\Auth\LoginController@login')->name('admin.login')->middleware('admin.guest');
Route::post('admin/onLogin', '\App\Http\Controllers\Admin\Auth\LoginController@onLogin')->name('admin.onLogin')->middleware('admin.guest');

Route::namespace ('\App\Http\Controllers\Admin')->middleware(['admin.auth'])->group(function () {
    //Home Page
    Route::get('/dashboard', 'HomeController@index')->name('home');
    //manage user
    Route::prefix('common')->group(function () {
        Route::get('/delete', 'CommonController@destroy')->name('common.destroy');
        Route::get('/print', 'CommonController@prints')->name('common.print');
        Route::get('/export', 'CommonController@export')->name('common.export');
        Route::post('/import', 'CommonController@import')->name('common.import');
        Route::get('/samplefiledownload', 'CommonController@sampleFileDownload')->name('common.samplefiledownload');

    });

    Route::prefix('admin')->group(function () {
        Route::resource('roles', 'RolesController', ['names' => 'admin.roles']);
        Route::resource('admin', 'Auth\AdminController')->except('update');
        Route::post('/admin/{admin}', 'Auth\AdminController@update')->name('admin.update');
        Route::get('/admin/{admin}', 'Auth\AdminController@show')->name('admin.show');

        Route::get('/profile/{id}', 'Auth\AdminController@profile')->name('admin.profile');
        Route::post('/changePassword', 'Auth\AdminController@changePassword')->name('admin.changePassword');
        Route::post('/admin-role/update/{id}', 'Auth\AdminController@roleUpdate')->name('admin.role.update');
        //Visitor Table
        Route::get('/visitor', 'VisitorController@VisitorIndex')->name('admin.VisitorIndex');
        Route::resource('user', 'UserController', ['names' => 'admin.user'])->except('update');
        Route::post('user/update/{user}', 'UserController@update')->name('admin.user.update');

        Route::get('readNotification',  function()
        {
            Auth::user()->unReadNotifications->markAsRead();
            return redirect()->back();
        })->name('admin.notification.read');

    });

        /**
         * Blog Route Start
         */
        Route::resource('blog', 'Blog\BlogController', ['names' => 'blog']);
        Route::get('/view/{blog}', 'Blog\BlogController@view')->name('blog.view');

        Route::resource('/category', 'Blog\CategoryController');
        Route::get('/category/{category}', 'Blog\CategoryController@show')->name('category.show');

        Route::resource('subcategory' , 'Blog\SubCategoryController');
        Route::get('/subcategory/list', 'Blog\SubCategoryController@ajaxGetData')->name('subcategory.ajaxdata');

        Route::resource('/tag', 'Blog\TagController');



        //manage comment
        Route::prefix('comment')->group(function () {
            Route::get('comment', 'Blog\CommentController@index')->name('comment.list');
            Route::get('approve/approve-list', 'Blog\CommentController@approveList')->name('comment.approve.list');
            Route::get('pending/pending-list', 'Blog\CommentController@pendingList')->name('comment.pending.list');
            Route::get('pending/list/approve/{id}', 'Blog\CommentController@pendingListApprove')->name('comment.pending.list.approve');
            Route::delete('delete/{id}', 'Blog\CommentController@destroy')->name('comment.destroy');
        });

        //filter data
        Route::prefix('filter')->group(function () {
            Route::get('/list', 'Blog\FilterController@index')->name('filter.view');
            Route::get('/list/data', 'Blog\FilterController@filter')->name('filter.list');
            Route::get('/subcategory/list', 'Blog\FilterController@ajaxGetSubcategoryData')->name('filter.getsubcategory');

        });


          /**
         * Blog Route Start
         */

    //manage Contact
    Route::prefix('contact')->group(function () {
        Route::get('/list', 'ContactController@index')->name('contact.index');

    });

    //manage setting
    Route::prefix('setting')->group(function () {
        Route::get('/list', 'SettingController@index')->name('setting.index');
        Route::get('/create', 'SettingController@create')->name('setting.create');
        Route::post('/store', 'SettingController@store')->name('setting.store');
        Route::post('/update/{id}', 'SettingController@update')->name('setting.update');
    });
    //banner
    Route::resource('banners', 'BannerController');

    Route::post('admin/logout', 'Auth\LoginController@onLogout')->name('admin.logout');
});


Route::namespace ('\App\Http\Controllers\Frontend')->group(function () {
    Route::get('/', 'HomeController@index')->name('client.home');
    Route::get('/login', 'Auth\LoginController@index')->name('client.loginProcess')->middleware('guest');
    Route::get('/register', 'Auth\LoginController@create')->name('client.register')->middleware('guest');
    Route::post('/register', 'Auth\LoginController@store')->name('client.regitration')->middleware('guest');
    Route::get('/send-otp', 'Auth\LoginController@sendOtp')->name('client.sendOtp')->middleware('guest');
    Route::post('/login', 'Auth\LoginController@login')->name('client.login')->middleware('guest');
    Route::prefix('user')->middleware('auth')->group(function () {
        Route::get('dashboard', 'User\UserController@index')->name('client.dashboard');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles, HasApiTokens, LogsActivity;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static $logName="user";
    protected static $ignoreChangedAttributes=["password"];
    protected static $logAttributes=["name", 'email', 'phone', 'username'];
    public function getDescriptionForEvent($eventName)
    {
        return   "User model has been {$eventName}";
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\BaseController;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;

class UserController extends BaseController
{
    public function index()
    {
        if (is_null($this->user) || !$this->user->can('user.view')) {
            abort(403, 'Sorry !! You are Unauthorized to view any User !');
        }

        return view('admin.pages.users.index', [
            'prefixname' => 'User',
            'title' => 'User List',
            'page_title' => 'User List',
            'users' => User::all(),
            'enumStatuses' => $this->enumStatuses,
        ]);

    }
    public function create()
    {
        if (is_null($this->user) || !$this->user->can('user.create')) {
            abort(403, 'Sorry !! You are Unauthorized to create any User !');
        }

            return view('admin.pages.users.create', [
                'prefixname' => 'User',
                'title' => 'User Create',
                'page_title' => 'User Create',
                'enumStatuses' => $this->enumStatuses,
            ]);

    }
    public function show(User $user)
    {
        if (is_null($this->user) || !$this->user->can('user.view')) {
            abort(403, 'Sorry !! You are Unauthorized to view any User !');
        }

            return view('admin.pages.users.details', [
                'prefixname' => 'User',
                'title' => 'User Create',
                'page_title' => 'User Create',
                'user' => $user,
                'enumStatuses' => $this->enumStatuses,
            ]);

    }



    public function store(UserStoreRequest $request, User $user)
    {
        if (is_null($this->user) || !$this->user->can('user.create')) {
            abort(403, 'Sorry !! You are Unauthorized to store any User !');
        }
        $user = $user->create($request->only('name','username','email','phone', 'status'));
        if ($user) {
            return redirect()->route('admin.user.index')->with('success', 'Data Added successfully Done');
        }
        return redirect()->back()->withInput()->with('failed', 'Data failed on create');
    }

    public function edit(User $user)
    {
        if (is_null($this->user) || !$this->user->can('user.edit')) {
            abort(403, 'Sorry !! You are Unauthorized to edit any User !');
        }
            return view('admin.pages.users.edit', [
                'prefixname' => 'User',
                'title' => 'User Create',
                'page_title' => 'User Create',
                'user' => $user,
                'enumStatuses' => $this->enumStatuses,
            ]);

    }

    public function update(UserUpdateRequest $request, User $user)
    {
        if (is_null($this->user) || !$this->user->can('user.edit')) {
            abort(403, 'Sorry !! You are Unauthorized to update any User !');
        }
            $user->update($request->only('name','username','email','phone', 'status'));
            if($user) {
                return redirect()->route('admin.user.index')->with('success', 'Data Added successfully Done');
            } else {
                return redirect()->back()->withInput()->with('error', 'Data Added Failed');
            }

    }
    public function destroy(User $user)
    {
        if (is_null($this->user) || !$this->user->can('user.delete')) {
            abort(403, 'Sorry !! You are Unauthorized to delete any User !');
        }
        $result = $user->delete();

        if ($result) {
            return redirect()->route('admin.user.index');
        } else {
            return redirect()->back();
        }

    }
}

app/Http/Controllers/Api/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\BaseController;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class UserController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = User::orderBy('id','DESC')->get();
        return $this->successResponse($data, 'All User List', Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request, User $user)
    {
        $data['user']= $user->create($request->only('name', 'email','username','phone'));
        return $this->successResponse($data, 'Registration Successfull', Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return $this->successResponse($user, 'User data', Response::HTTP_OK);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $data['user']= $user->update($request->only('name', 'email','username'));
        return $this->successResponse($data, 'User Updated', Response::HTTP_CREATED);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $result= $user->delete();
        return $this->successResponse($result, 'User Deleted', Response::HTTP_OK);
    }
}

app/Http/Controllers/Frontend/User/UserController.php
<?php

namespace App\Http\Controllers\Frontend\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('frontend.user.dashboard');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/users/create.blade.php
@extends('admin.layouts.master')
@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset('') }}app-assets/vendors/css/forms/wizard/bs-stepper.min.css">
    <link rel="stylesheet" href="{{ asset('') }}app-assets/vendors/css/forms/select/select2.min.css">
    <link rel="stylesheet" href="{{ asset('') }}app-assets/css/plugins/forms/form-validation.css">
@endsection

@section('page-style')
    <!-- Page css files -->
    <link rel="stylesheet" href="{{ asset('') }}app-assets/css-rtl/plugins/forms/form-validation.css">
    <link rel="stylesheet" href="{{ asset('') }}app-assets/css-rtl/plugins/forms/form-wizard.css">
@endsection
@section('content')
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">{{ request()->name }}</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a>
                                </li>
                                <li class="breadcrumb-item active">Create {{ request()->name }}
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">

            <section class="tooltip-validations" id="tooltip-validation">
                <div class="row">
                    <div class="col-12 p-5">
                        <div class="card">
                            <div class="card-header d-flex">
                                <div class="left">
                                    <a href="{{ url()->previous() }}" class="btn btn-dark btn-sm"><i
                                            class="fas fa-arrow-circle-left"></i> Back</a>
                                </div>
                                <div class="right">
                                    <a class="btn btn-primary btn-learge" href="{{ route('admin.user.index') }}"><i
                                            data-feather='eye'></i> View Admin</a>
                                    <a class="btn btn-dark btn-learge" href="{{ route('admin.user.create') }}"><i
                                            data-feather='plus'></i> Create New</a>
                                </div>
                            </div>
                        </div>
                        <!-- Modern Horizontal Wizard -->
                        @include('ErrorMessage')
                        <form class="mt-2" action="{{ route('admin.user.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label class="form-label" for="login-name">Name</label>
                                <input required id="name" placeholder="Name" type="name"
                                    class="form-control @error('name') is-invalid @enderror" name="name"
                                    value="{{ old('name') }}" autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="login-username">Admin Name</label>
                                <input required id="username" placeholder="Admin Name" type="username"
                                    class="form-control @error('username') is-invalid @enderror" name="username"
                                    value="{{ old('username') }}" autocomplete="username" autofocus>

                                @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="login-phone">Mobile</label>
                                <input required id="phone" placeholder="Mobile" type="phone"
                                    class="form-control @error('phone') is-invalid @enderror" name="phone"
                                    value="{{ old('phone') }}" autocomplete="phone" autofocus>

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label class="form-label" for="login-email">Email</label>
                                <input required id="email" placeholder="Email" type="email"
                                    class="form-control @error('email') is-invalid @enderror" name="email"
                                    value="{{ old('email') }}" autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="form-label" for="status">Status</label>
                                <select required name="status" id="status" class="form-control @error('status') is-invalid @enderror"
                                    value="{{ old('status') }}" autocomplete="status" autofocus>
                                    <option value="">Select Status</option>
                                    @foreach ($enumStatuses as $key => $status)
                                    <option   value="{{$key}}">{{$status}}</option>
                                     @endforeach
                                </select>

                                @error('status')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>



                            <button class="btn btn-primary btn-block" tabindex="4">Create</button>
                        </form>
                        <!-- /Modern Horizontal Wizard -->
                    </div>
                </div>
            </section>
            <!-- Tooltip validations end -->
        </div>
    </div>
@endsection

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.master')
@section('content')

    <!-- Advanced Search -->
    <section id="advanced-search-datatable">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Admin</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                                <li class="breadcrumb-item active">View Admin</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        @include ('components.flash-messages')

        <section id="advanced-search-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <a href="{{ url()->previous() }}" class="btn btn-dark btn-sm"><i class="fas fa-arrow-circle-left"></i> Back</a>
                            <div class="col-sm-10 mt-1">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <ol class="breadcrumb float-sm-right">
                                            <li style="margin: 2px;">
                                            <a class="btn btn-info btn-sm" href="{{ route('common.export',['extension'=>'csv','type'=>'admin']) }}">
                                                <i data-feather='file-text'></i> CSV</a>
                                            </li>
                                            <li style="margin: 2px;">
                                                <a class="btn btn-secondary btn-sm" href="{{ route('common.export',['extension'=>'xlsx','type'=>'admin']) }}">
                                                <i data-feather='download'></i> Excel</a>
                                            </li>
                                            <li style="margin: 2px;">
                                                <a class="btn btn-primary btn-sm" href="javascript:void(0)" onclick="showModal(' for Admin','admin')">
                                                <i data-feather='upload'></i> Import</a>
                                            </li>
                                            <li style="margin: 2px;">
                                            <a class="btn btn-danger btn-sm" href="{{ route('common.print',['action'=>'pdf','api'=>'admin']) }}" target="_blank">
                                            <i data-feather='file'></i> PDF</a></li>
                                            <li style="margin: 2px;">
                                            <a class="btn btn-warning btn-sm" href="{{ route('common.print',['action'=>'print','api'=>'admin']) }}" target="_blank">
                                            <i data-feather='printer'></i> Print</a></li>
                                            <li style="margin: 2px;"><a class="btn btn-primary btn-sm" href="{{ route('admin.user.index') }}"><i data-feather='eye'></i> View</a></li>
                                            <li style="margin: 2px;"><a class="btn btn-dark btn-sm" href="{{ route('admin.user.create') }}"><i data-feather='plus'></i> Create</a></li>
                                            <li style="margin: 2px;"><div class="btn-group">
                                                    <button type="button" class="btn btn-sm btn-outline-secondary">Column</button>
                                                    <button
                                                        type="button"
                                                        class="btn btn-sm btn-outline-secondary dropdown-toggle dropdown-toggle-split"
                                                        data-toggle="dropdown"
                                                        aria-haspopup="true"
                                                        aria-expanded="false"
                                                    >
                                                        <span class="sr-only">Toggle Dropdown</span>
                                                    </button>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Name</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Email</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Phone</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Address</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Admin Type</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Status</a>
                                                        <a class="dropdown-item" href="javascript:void(0);"><input name="checkbox" type="checkbox" readonly="readonly"/> Social Links</a>
                                                        <div class="col-md-12 p-1">
                                                            <button class="btn btn-sm btn-primary btn-block">Apply</button>
                                                        </div>
                                                    </div>
                                                </div></li>
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <hr class="my-0" />
                        <div class="col-sm-12">
                            <table class="table table-bordered table-responsive common-datatables" style="width:100%; padding: 10px">
                                <thead>
                                <tr>
                                    <th style="width: 3%">SL</th>
                                    <th style="width: 2%"><input name="checkbox" onclick='checkedAll();' type="checkbox" readonly="readonly" /></th>
                                    <th style="width: 10%">Action</th>
                                    <th style="width: 20%">Name</th>
                                    <th style="width: 10%">username</th>
                                    <th style="width: 10%">Email</th>
                                    <th style="width: 10%">Phone</th>
                                    <th style="width: 10%">Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($users!="")
                                    @foreach($users as $key=>$user)
                                        <tr id="tablerow{{ $key }}">
                                        <td>{{ $user->id }}</td>
                                        <td><input type="checkbox"  name="summe_code[]" id="summe_code" value="{{ $user->id }}" /></td>
                                        <td class="text-nowrap">
                                            <a href="{{ route('admin.user.show',$user->id) }}"><i data-feather='eye'></i></a>
                                            <a href="{{ route('admin.user.edit',$user->id) }}"><i data-feather='edit'></i></a>
                                            <a href="#" onclick="singleDelete({{ $user->id }},'admin');"><i data-feather='trash-2'></i></a>
                                            <a href="#"><i data-feather='more-vertical'></i></a>
                                        </td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->username }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->phone }}</td>
                                        <td>
                                            @php

                                            $btnClass=['danger', 'success', 'warning', 'info', 'danger']
                                        @endphp
                                        @foreach ($enumStatuses as $key => $status)
                                            @if ($user->status == $key)
                                                <button class="btn btn-sm btn-{{ $btnClass[$key]}}">
                                                        {{$enumStatuses[$key]}}
                                                    </button>
                                            @endif
                                        @endforeach
                                        </td>
                                    </tr>
                                    @endforeach
                                @endif

                                </tbody>

                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    </section>
    <!--/ Advanced Search -->


@endsection

@section('page-script')
@endsection